spring:
  application:
    name: spring-security
    jwtSecret: J3Q0kcHXcVpP6m0A4FjtIczPCRlQ+vEU9/Cwn+8S22w= # Base64-encoded 256-bit key
    jwtExpirationMs: 86400000 # 1 day

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:

  # Spring Security Configuration
  security:
    user:
      name: admin
      password: admin123

  # H2 Database Configuration
  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

server:
  port: 8080

# Logging
logging:
  level:
   # org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG