spring:
  application:
    name: spring-security
    jwtSecret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo= # Base64-encoded 256-bit key
    jwtExpirationMs: 86400000 # 1 day

  # Spring Security Configuration
  security:
    user:
      name: admin
      password: admin123

  # H2 Database Configuration
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:


  # MySQL Database Configuration
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql:

server:
  port: 8080