spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # ok per sviluppo e testing. Da evitare in produzione!
    show-sql: true
    properties:
      hibernate.format_sql: true

security:
  jwt:
    secret-key: this-is-a-secret-key