spring:
  application:
    name: spring-security

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

# Spring Security Configuration
#  security:
#    user:
#      name: admin
#      password: admin123
