spring:
  application:
    name: spring-security

  # Spring Security Configuration
  security:
#    user:
#      name: admin
#      password: admin123

  # H2 Database Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
        mode: always

server:
  port: 8080