spring:
  application:
    name: spring-security-course
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

server:
  port: 8080

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # ok per sviluppo e testing. Da evitare in produzione!
    show-sql: true
    properties:
      hibernate.format_sql: true

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:this-is-a-dev-secret}
    expiration: 3600000  # Millisecondi (3600000ms = 1 ora)
    token:
      header: Authorization
      prefix: Bearer # Lasciare uno spazio dopo il prefisso

#  "username": "tizio1",
#   "role": "[ROLE_USER]"
# JWT: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMCIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE3NDQzODI2MTIsInVzZXJuYW1lIjoidGVzdGVyLTEifQ.APZAiWpXkAF1exHoeNPESsCmnE-ifFGLb0kE63LMv44